; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

; utilizando uma biblioteca para gerenciamento do Download, nesta compilação nosso [CODE] realiza a tarefa para o Framework 4.0 :B
#include ReadReg(HKEY_LOCAL_MACHINE,'Software\Sherlock Software\InnoTools\Downloader','ScriptPath','')

#define MyAppName "Atualização NDD E-Agente 3.4.6.0"
#define MyAppVersion "Atualização NDD E-AGENTE 3.4.6.0 - 09-06-2015"
#define MyAppPublisher "Expresso São Miguel Ltda."
#define MyAppURL "http://www.expressosaomiguel.com.br"

[Setup]

AppId={{2920414C-4166-434A-896A-3A6BF223B876}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
PrivilegesRequired=admin
DefaultDirName={pf}\Expresso Sao Miguel\Agencia
DisableDirPage=true
DefaultGroupName=Agencia
DisableProgramGroupPage=true
OutputDir=C:\INSTALADOR\Projeto - Compilador
OutputBaseFilename=Atualizacao_E-AGENTE_3.4.6.0
SetupIconFile=C:\INSTALADOR\Projeto - Compilador\icone.ico
Compression=lzma
SolidCompression=true
WizardImageFile=C:\INSTALADOR\Projeto - Arquivos\Logos\logo_novo.bmp
WizardSmallImageFile=C:\INSTALADOR\Projeto - Arquivos\Logos\logo_direito.bmp
Password=
DisableStartupPrompt=true
UsePreviousSetupType=false
DisableFinishedPage=false
UsePreviousUserInfo=false
UserInfoPage=false
AllowCancelDuringInstall=false
ShowLanguageDialog=no
TerminalServicesAware=false
UsePreviousTasks=false
ShowComponentSizes=false
RestartIfNeededByRun=false
ChangesAssociations=true
WizardImageStretch=false
WizardImageBackColor=clWhite

[Languages]

Name: brazilianportuguese; MessagesFile: compiler:Languages\BrazilianPortuguese.isl

;//-----------------------------------------------------------------------------------------------------------------------------------------------//

[Files]

;Arquivos novos
Source: ..\Projeto - Arquivos\Registrador\*; DestDir: {pf}\Expresso Sao Miguel\Agencia\registrador; Flags: ignoreversion

;//-----------------------------------------------------------------------------------------------------------------------------------------------//

[Registry]

;desabilitado UAC do perfil do usuário, para poder registrar a .dll com o arquivo .bat
Root: HKLM; Subkey: SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System; ValueType: dword; ValueName: EnableLUA; ValueData: 0; Flags: noerror

;//-----------------------------------------------------------------------------------------------------------------------------------------------//

[Run]

;após instalação da att. é forçada a reincialização do computador
Filename: {pf}\Expresso Sao Miguel\Agencia\registrador\reset.bat; Flags: waituntilidle runminimized

;//-----------------------------------------------------------------------------------------------------------------------------------------------//

[Code]


//incialização do setup, sempre chamada pelo Inno ao iniciar o setup
procedure InitializeWizard();

var
    regvalor,arquivo: String;
    ErrorCode: Integer;

begin
	//comandos que realiza a finalização dos executaveis;

	//idpAddFileSize('ftp://arquivos:ti@ftp#@expressosaomiguel.com.br/temp/logdev.txt', 'ExpandConstant('{app}\\NDDigital\e-Agente\log\logdev.txt'), 'LOG_NDD');

	ShellExec('open',  'taskkill.exe', '/f /im Datacenter.Agent.Service.exe','',SW_HIDE,ewNoWait,ErrorCode);
    ShellExec('open',  'taskkill.exe', '/f /im NDDigital.eForms.PrintService.exe','',SW_HIDE,ewNoWait,ErrorCode);
    ShellExec('open',  'taskkill.exe', '/f /im NDDigital.eForms.PrintServiceGuardian.exe','',SW_HIDE,ewNoWait,ErrorCode);
    ShellExec('open',  'taskkill.exe', '/f /im NDDigital.eForms.ImpressionControlService.exe','',SW_HIDE,ewNoWait,ErrorCode);
	ShellExec('open',  'taskkill.exe', '/f /im DCSServer\DCSServer.exe','',SW_HIDE,ewNoWait,ErrorCode);
	ShellExec('open',  'taskkill.exe', '/f /im Datacenter.Agent.Monitor.Contingency.exe','',SW_HIDE,ewNoWait,ErrorCode);


    // realiza a leitura do valor no registro, pra ver se ele está instalado com a versão correta ou não;
    begin
    RegQueryStringValue(HKEY_LOCAL_MACHINE,('SOFTWARE\JavaSoft\Java Runtime Environment\1.8.0_51\MSI'),'PRODUCTVERSION',regvalor);
		//MsgBox('VALOR DO RESGISTRO = "' + regvalor + '"', mbInformation, MB_OK);
    end;

    //se o regvalor igual a "NDDigital e-Datacenter e-Agente" então é necessária a atualização, do contrario finaliza a instalação.
    if (regvalor <> 8.0.510) then begin

      // definir o caminho do arquivo, ao terminar o download, é onde o arquivo será armazenado (não vou deletar após a instalação por precaução)
      arquivo := expandconstant('{tmp}\eAgente3.4.6.0.exe');
      // não está instalado. Exibir a mensagem para o usuário o informando:
      MsgBox('Para continuar a instalação é necessário fazer o download da Atualização NDDigital E-Agente 3.4.6.0'#13#13
			 'ESSE PROCESSO É REALIZADO AUTOMATICAMENTE'#13#13#13
			 'APÓS A INSTALAÇÃO SEU COMPUTADOR SERÁ REINICIADO, SALVE TODOS OS SEUS ARQUIVOS E AGUARDE!'#13#13#13
			 'Dúvidas entre em contato com o Suporte T.I. - (49) 3361-6661'#13#13, mbInformation, MB_OK);
          //iniciar o itd
          itd_init;
          //adiciona um arquivo na fila de downloads. (pode se adicionar quantos forem necessários)
          itd_addfile('http://downloads.nddigital.com.br/Datacenter/Update%20e-Agente%20e-Datacenter%203.4.6.0.exe', arquivo);
          //aqui dizemos ao itd que é para fazer o download após o inno exibir a tela de preparação do setup
          itd_downloadafter(wpReady);
    end;
end;

//-----------------------------------------------------------------------------------------------------------------------------------------------//

//Este método é chamado pelo Inno ao clicar em próximo. Neste momento a interface já está criada

procedure CurStepChanged(CurStep: TSetupStep);

var
    ResultCode: Integer;
    arquivo  : String;

	begin
	arquivo := expandconstant('{tmp}\eAgente3.4.6.0.exe')

if CurStep = ssInstall then begin
    // para evitar erros, validamos se o arquivo foi baixado. Se não foi, continua com o setup.
    if fileExists(arquivo) then begin
		MsgBox('A INSTALAÇÃO PODERÁ DEMORAR ALGUNS MINUTOS, POR FAVOR AGUARDE!'#13#13,mbInformation, MB_OK);
        // foi baixado. Executar o instalador.
       if not ShellExec('', arquivo,'/S', '', SW_SHOW, ewWaitUntilTerminated, ResultCode) then begin
          // Xi! Deu erroww.
         if ResultCode <> 0 then begin
              MsgBox('Erro ao tentar instalar o Update - Contate o Suporte T.I. Expresso São Miguel - (49) 3361-6661' + arquivo + chr(13) + SysErrorMessage(ResultCode), mbError, mb_Ok);
         end;
       end
    end;
end;
end;

//-----------------------------------------------------------------------------------------------------------------------------------------------//


//-----------------------------------------------------------------------------------------------------------------------------------------------//
